<a href="https://colab.research.google.com/github/SharonCamacho/Data-Science-FEM-Study-Group/blob/master/2_1_Lineal_Algebra_Practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Taller tomado de @alvarezmeneses

https://github.com/salvarezmeneses/DataScience2020/blob/master/2_1_Lineal_Algebra_Practice_1.ipynb


In [0]:
import numpy as np

# Question 1.

* Print the sum of matrixes A and B

$$ A =
\left(\begin{array}{cc} 
1 & 2\\
3 & 4\\
5 & 6
\end{array}\right) + B =
\left(\begin{array}{cc} 
6 & 5\\
4 & 3\\
2 & 1 
\end{array}\right)
$$ 

In [2]:
# Answer 1.
'Your code here'
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[6,5],[4,3],[2,1]])
print(a+b)

[[7 7]
 [7 7]
 [7 7]]


# Question 2

* Print the sum of matrix + scalar.

$$ M =
\left(\begin{array}{cc} 
6 & 3\\
9 & 5\\
4 & 8
\end{array}\right) + N =
\left(\begin{array}{cc} 
2.5 \\ 
\end{array}\right)
$$ 

In [3]:
# Answer 2.
'Your code here'
m=np.array([[6,3],[9,5],[4,8]])
n=2.5
print(m+n)

[[ 8.5  5.5]
 [11.5  7.5]
 [ 6.5 10.5]]


# Question 3.

* Print the transposed matrix of  $J$  -->  $J^t$. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [4]:
# Answer 3.
'Your code here'
j=np.array([[9,2,3],[3,7,4],[5,6,9]])
jt=j.T
print(jt)

[[9 3 5]
 [2 7 6]
 [3 4 9]]


# Question 4.

* For the $ J ^ t $ matrix, calculate your transpose to obtain the original matrix J. 

$$ J =
\left(\begin{array}{cc} 
9 & 2 & 3\\
3 & 7 & 4 \\
5 & 6 & 9
\end{array}\right) 
$$ 

In [5]:
# Answer 4.
'Your code here'
print(jt.T)

[[9 2 3]
 [3 7 4]
 [5 6 9]]


# Question 5.

* 
What are the missing values? 

$$
\left(\begin{array}{cc} 
? & 2\\
0 & 2
\end{array}\right)
\left(\begin{array}{cc} 
1 & 0 \\ 
1 & ? 
\end{array}\right)
$$ 

 * so that the answer is like this:
$
\left(
 \begin {array}{ll} 
1 & 0 \\
0   & 0
\end{array}
\right)
$

- [ A ] = 1 y 1
- [ B ] = 0 y 1
- [ C ] = 1 y 0
- [ D ] = 0 y 0

*  Print the result and the answer.

In [6]:
# Answer 5.
'your code here'
# creacion de matrices 
A = np.array([[1,2],[0,2]])
d = np.array([[1,0],[1,0]])

# calculo de producto entre matrices
C = A * d
# imprimir la respuesta
print('la respuesgta es la C:',"\n", C)

la respuesgta es la C: 
 [[1 0]
 [0 0]]


# Question 6.
* ¿ What is the dot product matrixes  $L$ y $K$ = : ?

$$ L =
\left(\begin{array}{cc} 
3 & 5 \\
7 & 1 \\
\end{array}\right) K =
\left(\begin{array}{cc} 
3 & 12  \\
6 & 4  \\
\end{array}\right)
$$ 

In [7]:
# Answer 6.
'your code here'
L=np.array([[3,5],[7,1]])
K=np.array([[3,12],[6,4]])
print(L.dot(K))

[[39 56]
 [27 88]]


# Question 7.

* ¿ What is the determinant of the following matrix  ? (Print the answer)

$
\left(
\begin {array}{ll} 
1 & 2 & 0 \\
1 & 2 & 0 \\
0 & 1 & 1 \\
\end{array}
\right)
$

- [ A ] = 1 
- [ B ] = 0 
- [ C ] = 5
- [ D ] = -5



In [8]:
# Answer 7.
'your code here'
D = np.array([[1,2,0],[1,2,0], [0,1,1] ])

determinant = np.linalg.det(D)

print('la respuesgta es la B:', determinant)

la respuesgta es la B: 0.0


# Question 8.

* ¿ What is the determinant of the following matrix ? (Print the answer)

$
\left(
\begin {array}{ll} 
0 & 1 & 1 \\
1 & 0 & 0 \\
0 & 0 & 1 \\
\end{array}
\right)
$

- [ A ] = 0 
- [ B ] = -1 
- [ C ] = 3
- [ D ] = 1


In [10]:
# Answer 8.
'your code here'
F = np.array([[0,1,1],[1,0,0], [0,0,1] ])

determinant_2 = np.linalg.det(F)

print('la respuesgta es la B:', determinant_2)

la respuesgta es la B: -1.0


# Question 9

* ¿What is the missing value?
$$ 
\left(\begin{array}{cc} 
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right) 
\left(\begin{array}{cc} 
0 \\ 
? \\
0 \\
\end{array}\right) =
\left(\begin{array}{cc} 
4 \\ 
10 \\
16 \\
\end{array}\right)
$$ 

In [17]:
# creacion de matrices 
m_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m_2 = np.array([0,2,0])

# calculo de producto entre matrices
resultante = m_1 * m_2
# imprimir la respuesta
print('El valor Faltantes es 2:',"\n", resultante)

El valor Faltantes es 2: 
 [[ 0  4  0]
 [ 0 10  0]
 [ 0 16  0]]
